python evaluate.py \
    --user-dir ../../graphormer \
    --num-workers 32 \
    --ddp-backend=legacy_ddp \
	--user-data-dir testing_dataset \
	--dataset-name RT_test \
    --task graph_prediction \
	--criterion rmse \
	--arch graphormer_base \
    --encoder-layers 8 \
    --encoder-embed-dim  512 \
    --encoder-ffn-embed-dim 512 \
    --encoder-attention-heads 64 \
    --mlp-layers 5 \
    --batch-size 64 \
    --num-classes 1 \
    --save-dir '/home/cmkstien/Graphormer_RT/cmodel' \
    --split train \